### ISSUE TITLE
repo down?

### ISSUE THREAD

**Issue by madgabz** [blacksky3/linux-zen#1]
https://repo.blacksky3.com/x86_64/linux-zen seems to be down for a few days?

I've configured pacman.conf exactly as posted here, and its been working flawlessly for several weeks, until app 2 days ago. manually trying to access the above address w browser (firefox) also times out and gives cloudflare site!

**Comment by blacksky3** [comment]
Hi the server is down for the moment. It will be up in the next few days. We are working on the server and VM to

**Comment by blacksky3** [comment]
Hi The server is back online finaly. And I bump the version of zen kernel. Let me know if everything is good on your side and I will close the issue
